services:
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/:/etc/mysql/conf.d/

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    env_file:
      - .env
    volumes:
      - ./docker/redis/redis.conf.tpl:/etc/redis/redis.conf.tpl
    entrypoint: >
      /bin/sh -c "
        apk add --no-cache gettext &&
        envsubst < /etc/redis/redis.conf.tpl > /etc/redis/redis.conf &&
        exec redis-server /etc/redis/redis.conf
      "

volumes:
  db_data:
