"""init

Revision ID: 45dd304438ec
Revises:
Create Date: 2025-05-27 09:32:31.623830

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45dd304438ec"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parcel_type",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "parcel",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("declared_value_usd", sa.Float(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("delivery_cost_rub", sa.Float(), nullable=True),
        sa.Column("parcel_type_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["parcel_type_id"],
            ["parcel_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parcel")
    op.drop_table("parcel_type")
    # ### end Alembic commands ###
